### ISSUE TITLE
Paper title shows odd escape instead of unicode

### ISSUE THREAD

**Issue by rcplane** [cul-it/arxiv-search#71]
https://beta.arxiv.org/search/?query=what+is+your+favorite+color&searchtype=all

L\'evy looks odd compared to Lévy, is this behavior expected?
re: https://arxiv.org/abs/1711.04210v1

![screen shot 2018-02-13 at 4 22 38 pm](https://user-images.githubusercontent.com/1978942/36174692-01a54228-10db-11e8-9021-403acfe078b0.png)

**Comment by eawoods** [comment]
@erickpeirson @mhl10 is this because the new system doesn't support pidgin TeX (and that this character is notated as such rather than as unicode)? I had noticed another title where the curly-braces format doesn't work, so I suspect this to be the case.

**Comment by erickpeirson** [comment]
I'll defer to @mhl10 on this. But I do note that the character is displayed correctly on the abs page.

**Comment by eawoods** [comment]
I wonder if it has to do with the way we configured MathJax for the new system - had to do some regex adjustment to use the CDN. It’s a different implementation than the old system (and thus would show correctly on the abs page but not on our new pages, until we fix it).

- Liz

On Feb 15, 2018, at 7:43 AM, Erick <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll defer to @mhl10<https://github.com/mhl10> on this. But I do note that the character is displayed correctly on the abs page.

**Comment by erickpeirson** [comment]
Don't think it's MathJax, since it displays correctly on the abs page even with JavaScript disabled

**Comment by mhl10** [comment]
The problem has do with our use of the raw title for display rather than the UTF-8-encoded title (``title_utf8``). ``title_utf8`` contains the UTF-8 forms of the single-character texisms (like \`e), regardless of whether that texism was delimited by $. For most cases this is OK, but it can look odd when certain encoded characters also happen to be delimited by $, which means MathJax will process them. I think the long term solution is to create a jinja texism filter that only converts the texism if it's *not* delimited by $.

Regarding MathJax, it would be good to use arXiv's CDN since MathJax is deprecating theirs: https://static.arxiv.org/MathJax-2.7.0/
There are also a few differences in the MathJax config that would be good to revisit in the next round of changes.

**Comment by erickpeirson** [comment]
ARXIVNG-291 | Reintroduce title_utf8 in /docmeta response and in document map

**Comment by erickpeirson** [comment]
@mhl10 Was this fixed by #78 ?

**Comment by mhl10** [comment]
@erickpeirson fixed in PR #90
